<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="css/animate.css" />
    <!-- master custom CSS -->
    <link rel="stylesheet" href="css/master.css" />

    <!-- Fonts CSS -->
    <link rel="stylesheet" href="css/fontello-codes.css" />
    <link rel="stylesheet" href="css/fontello-embedded.css" />
    <link rel="stylesheet" href="css/fontello.css" />

<link href="style.css" rel="stylesheet" type="text/css" media="screen" />
    <title>Process Support Services</title>
	 <?php include('header.php'); ?>
	
  </head>
  <body style="background-image: url(images/bgi.jpg); background-repeat: repeat ">
   

	<br><br><br><br><br>
	  
	 
	 <h2 style="text-align:center"> <font color="black">Process Support Services</font> </h2>
	 
	<div align="center" style="padding-top:120px"; >  </div>
	
	
	<div id="two-columns1">
		<div id="column1" >
		
			<h2 ><font color="#061D5E">Back Office administration</h2>
			
			<div style="border-style: solid"> <img src="images/backofc-admin.png"  width="454" height="275" /></div>
			
			<p style="text-align:justify; color:black; font-size:16px;">Back Office Administration represents a range of processes that are necessary for the advancement of general business functions, failure to handle them effectively can have a detrimental effect on the core business. At CassiXcom, we offer a wide range of Back Office Administration services according to the requirements of our clients. Our team will ensure total commitment, dedication, accuracy and efficiency. As every organisation operates on its own unique way, administrative services are developed on a per client basis and according to the specifications required. Our back-office team will work together with you to streamline your administrative activities for optimal efficiency. Talk to us today for more details.</p>
			
		</div>
		<div id="column2">
			<h2><font color="#061D5E">Sales Support</h2>
			
			
			<div style="border-style: solid"> <img src="images/sales-support.jpg"  width="454" height="275" /></div>
			
			<p style="text-align:justify; color:black; font-size:16px;">Reliable sales support and intelligence go long way in building up your sales pipeline! Our Sales support professional’s team, enhance your conversion rate by qualifying leads, building prospect lists and auctioning sales opportunities. We at CassiXcom, not only build a robust sales pipeline but also keep it flowing with a steady stream of productive qualified leads. Efficient and effective sales support specialists from CassiXcom can strengthen your sales funnel and fuel your revenue growth. We help you improve the productivity of your sales force by focusing on their short, medium and long term goals and close your sales deals competently and smoothly. Talk to us today.</p>
			
		</div>
		
		</div>
		
		
		
	<div id="two-columns2">	
		
	<div id="column3">
			<h2><font color="#061D5E">Accounting and Finance administration</h2>
			
			<div style="border-style: solid"> <img src="images/account-admin.jpg"  width="454" height="275" /></div>
			
			<p style="text-align:justify; color:black; font-size:16px;">We offer bespoke financial solutions that involve accounting, finance Management work as well. Healthy accounts display the good status of an organization. Accounting services at CassiXcom are generated by highly expert people providing their valuable support in making the account clearly understandable.  We offer end-to-end accounting, financial and advisory services with the idea that large corporates are not the only companies that should benefit from experienced finance professionals. Contact us for account and financial administration.</p>
			
		</div>	
		
		
		<div id="column4">
			<h2><font color="#061D5E">Customised Functional Area Support</h2>
			
			
			<div style="border-style: solid"> <img src="images/customised-support.jpg"  width="454" height="275" /></div>
			
			<p style="text-align:justify; color:black; font-size:16px;">We offer bespoke support to suit your business requirements – examples include engineering support for construction and manufacturing industries. Design services (AutoCAD, 3d design etc.) for manufacturing. Essentially if you need support and you can’t find it in the marketplace, talk to us today.</p>
			
		</div>
		</div>
		
	</div>
	<?php include('footer.php'); ?>


  </body>
</html>